### ISSUE TITLE
Helpdesk still shows "needs authentication" after logging in

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Android#4] opened 2016-01-06 16:44 UTC
##### steps to reproduce:
- start app (not logged in)
- go to helpdesk pane (it should display "needs authentication" message)
- open sidebar, click header to open login page
- log in
- login page closes, helpdesk pane still says "needs authentication"

if i start from the notifications pane, log in, and then go to the helpdesk pane, it displays the form as it should

**Comment by ryanrampage1** [comment] 2016-01-10 00:05
fixed by changing where the profile is

**Comment by ryanrampage1** [comment] 2016-01-10 00:07
was caused by login being in a new activity, once logged in it went back to the main activity without hitting oncreate of the fragment because it still had an instance on the stack. by doing it in the fragment it destroys the help desk frag, and creates a new one when you come back to it

**Closed as completed by ryanrampage1** 2016-01-10 00:07 UTC
Labels: bug
